In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df = pd.read_csv('DataSet/ecommerce_orders.csv')

In [29]:
df.head()

,OrderID,Customer_Age,City,Category,Product Name,Quantity,Price,Discount_pct,Payment Method,Order_Date,Rating
0,ORD1073,46.0,Bangalore,Beauty,Shampoo,2,7.73,NaN,UPI,26/05/2023,5.0
1,ORD1067,NaN,NaN,Beauty,Shampoo,5,74.76,0.0,Cash,2023-04-16,NaN
2,ORD1411,150.0,Bangalore,Toys,Doll,-1,163.06,20.0,Net Banking,01/05/2023,NaN
3,ORD1477,150.0,Mumbai,Electronics,Power Bank,0,41.53,0.0,UPI,26/01/2024,5.0
4,ORD1090,NaN,Bangalore,Electronics,Wireless Mouse,3,238.75,0.0,Debit Card,2023-02-27,NaN

In [30]:
df.tail()

,OrderID,Customer_Age,City,Category,Product Name,Quantity,Price,Discount_pct,Payment Method,Order_Date,Rating
560,ORD1457,-5.0,Hyderabad,Clothing,Jacket,1,10.62,0.0,UPI,2024-11-13,1.0
561,ORD1361,44.0,Mumbai,Toys,Lego Set,5,197.14,0.0,Credit Card,2023-11-20,4.0
562,ORD1440,NaN,Delhi,Beauty,Lipstick,4,45.27,15.0,Credit Card,2024-10-08,3.0
563,ORD1175,NaN,Chennai,Toys,Doll,0,324.36,5.0,UPI,2023-05-02,NaN
564,ORD1123,150.0,Delhi,Sports,Jump Rope,1,162.41,20.0,UPI,22/03/2024,4.0

In [31]:
df.sample(10)

,OrderID,Customer_Age,City,Category,Product Name,Quantity,Price,Discount_pct,Payment Method,Order_Date,Rating
413,ORD1425,55.0,NaN,Sports,Gym Bag,5,33.49,NaN,NaN,2023-09-07,NaN
190,ORD1025,43.0,Delhi,Electronics,Webcam,1,230.75,5.0,NaN,10/07/2023,4.0
389,ORD1319,150.0,Delhi,Toys,RC Car,1,82.44,15.0,Credit Card,2024-09-01,4.0
5,ORD1346,52.0,Mumbai,Beauty,Face Cream,0,309.85,0.0,Cash,2024-05-31,5.0
181,ORD1369,NaN,mumbai,Home & Kitchen,Frying Pan,1,101.92,5.0,UPI,2023-05-22,NaN
6,ORD1514,-5.0,Chennai,Beauty,Face Mask,0,433.70,0.0,UPI,2024-12-24,NaN
495,ORD1382,150.0,mumbai,Toys,Puzzle,4,349.88,NaN,UPI,2023-09-20,NaN
401,ORD1003,24.0,Bangalore,Books,Notebook,1,367.34,20.0,Debit Card,2023-06-13,5.0
130,ORD1263,63.0,Kathmandu,Electronics,USB Cable,1,74.34,0.0,Cash,2023-02-23,2.0
400,ORD1426,40.0,Kathmandu,Electronics,USB Cable,1,277.02,10.0,UPI,2024-01-27,4.0

###  **Column names** — inconsistent spacing/casing. Normalize to snake_case first, makes everything else easier.

In [32]:
df.columns

Index(['OrderID', 'Customer_Age', 'City', 'Category', 'Product Name',
       'Quantity', 'Price', 'Discount_pct', 'Payment Method', 'Order_Date',
       'Rating'],
      dtype='object')

In [35]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r'[^a-z0-9]+', '_', regex=True)
    .str.strip('_')
)
print(df.columns)

Index(['orderid', 'customer_age', 'city', 'category', 'product_name',
       'quantity', 'price', 'discount_pct', 'payment_method', 'order_date',
       'rating'],
      dtype='object')

### **Load + first look** — `.shape`, `.head()`, `.info()`, `.dtypes`. Get oriented before changing anything.

In [37]:
df.sample(5)

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
256,ORD1357,-5.0,mumbai,Electronics,Wireless Mouse,2,18.12,0.0,NaN,2024-11-01,4.0
549,ORD1534,59.0,Delhi,Home & Kitchen,Cutting Board,0,279.94,10.0,UPI,2024-08-11,NaN
133,ORD1176,150.0,Mumbai,Books,Textbook,4,91.31,0.0,Debit Card,27/05/2024,5.0
160,ORD1498,150.0,Mumbai,Clothing,Sneakers,5,43.48,5.0,Cash,2024-04-30,1.0
534,ORD1494,38.0,Bangalore,Home & Kitchen,Lamp,-1,98.12,0.0,NaN,2023-05-19,3.0

In [38]:
df.shape

(565, 11)

In [39]:
df.head()

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
0,ORD1073,46.0,Bangalore,Beauty,Shampoo,2,7.73,NaN,UPI,26/05/2023,5.0
1,ORD1067,NaN,NaN,Beauty,Shampoo,5,74.76,0.0,Cash,2023-04-16,NaN
2,ORD1411,150.0,Bangalore,Toys,Doll,-1,163.06,20.0,Net Banking,01/05/2023,NaN
3,ORD1477,150.0,Mumbai,Electronics,Power Bank,0,41.53,0.0,UPI,26/01/2024,5.0
4,ORD1090,NaN,Bangalore,Electronics,Wireless Mouse,3,238.75,0.0,Debit Card,2023-02-27,NaN

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   orderid         565 non-null    object
 1   customer_age    439 non-null    float64
 2   city            495 non-null    object
 3   category        565 non-null    object
 4   product_name    565 non-null    object
 5   quantity        565 non-null    int64
 6   price           565 non-null    float64
 7   discount_pct    496 non-null    float64
 8   payment_method  479 non-null    object
 9   order_date      565 non-null    object
 10  rating          417 non-null    float64
dtypes: float64(4), int64(1), object(6)
memory usage: 48.7+ KB

In [45]:
df.dtypes

orderid            object
customer_age      float64
city               object
category           object
product_name       object
quantity            int64
price             float64
discount_pct      float64
payment_method     object
order_date         object
rating            float64
dtype: object

###  **Missing values** — `.isna().sum()` to see where. Then per column, decide: drop, fill with mean/median/mode, fill "Unknown", or leave? Don't use the same strategy everywhere — justify each one.

In [47]:
df.isna().sum()

orderid             0
customer_age      126
city               70
category            0
product_name        0
quantity            0
price               0
discount_pct       69
payment_method     86
order_date          0
rating            148
dtype: int64

In [49]:
df['customer_age'] = df['customer_age'].fillna(df['customer_age'].median())

In [50]:
df['city'] = df['city'].fillna("Unknown")

In [51]:
df['discount_pct'] = df['discount_pct'].fillna(0)

In [52]:
df['payment_method'] = df['payment_method'].fillna('Unknown')

In [53]:
df.isna().sum()

orderid             0
customer_age        0
city                0
category            0
product_name        0
quantity            0
price               0
discount_pct        0
payment_method      0
order_date          0
rating            148
dtype: int64

### **Duplicates**
  - Full-row duplicates: `.duplicated()`
  - Suspicious ID duplicates: same OrderID with *different* data in other columns — that's not a real duplicate, that's a data entry error. Check `.duplicated(subset=['OrderID'])` and inspect those rows.

In [55]:
df.duplicated().sum()

np.int64(13)

In [59]:
df[df.duplicated()]

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
150,ORD1161,46.0,mumbai,Toys,Action Figure,2,187.05,0.0,Net Banking,20/05/2024,5.0
251,ORD1271,19.0,Bangalore,Home & Kitchen,Coffee Mug,4,405.63,0.0,Cash,2024-08-05,2.0
289,ORD1313,150.0,Bangalore,Home & Kitchen,Lamp,0,17.55,0.0,Unknown,2024-05-06,5.0
307,ORD1296,-5.0,DELHI,Sports,Jump Rope,3,263.51,0.0,Net Banking,2024-05-06,5.0
368,ORD1365,150.0,Kathmandu,Clothing,Sneakers,1,471.03,5.0,Credit Card,2024-02-24,4.0
372,ORD1208,150.0,Bangalore,Sports,Dumbbell,-1,333.43,20.0,Cash,2024-04-29,1.0
393,ORD1136,150.0,DELHI,Toys,Doll,1,164.99,15.0,Debit Card,2024-09-03,NaN
429,ORD1462,46.0,mumbai,Home & Kitchen,Lamp,5,326.36,0.0,Debit Card,2023-10-09,2.0
430,ORD1066,20.0,mumbai,Toys,Action Figure,2,273.63,10.0,Debit Card,2023-08-21,5.0
450,ORD1535,42.0,mumbai,Books,Comic,4,385.65,15.0,Debit Card,2024-08-27,NaN
452,ORD1307,150.0,Mumbai,Beauty,Face Cream,3,260.57,0.0,Cash,2023-09-20,NaN
472,ORD1424,-5.0,Delhi,Books,Novel,-1,249.74,0.0,Net Banking,2023-03-16,5.0
543,ORD1533,150.0,Unknown,Toys,Board Game,5,498.34,0.0,Credit Card,14/05/2024,5.0

In [58]:
df.duplicated(subset=['orderid']).sum()

np.int64(19)

In [61]:
df = df.drop_duplicates()

In [63]:
df.duplicated().sum()

np.int64(0)

In [64]:
df.duplicated(subset=['orderid']).sum()

np.int64(6)

In [66]:
df[df.duplicated(subset=['orderid'])]

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
124,ORD1226,150.0,Hyderabad,Electronics,Power Bank,2,125.77,0.0,Cash,2024-04-06,3.0
222,ORD1001,-5.0,Delhi,Clothing,Jeans,0,276.87,20.0,Credit Card,2024-08-25,2.0
284,ORD1001,41.0,Pokhara,Electronics,Power Bank,2,275.08,0.0,Net Banking,2023-01-03,NaN
308,ORD1001,-5.0,Hyderabad,Books,Textbook,1,347.01,0.0,Net Banking,2023-12-02,5.0
385,ORD1001,150.0,mumbai,Electronics,USB Cable,2,41.65,0.0,Credit Card,2023-11-28,NaN
551,ORD1001,150.0,Delhi,Beauty,Face Cream,1,190.40,0.0,Unknown,2023-10-09,NaN

In [68]:
df[df['orderid'] == 'ORD1226']

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
21,ORD1226,150.0,Hyderabad,Electronics,Power Bank,2,6288.50,0.0,Cash,2024-04-06,3.0
124,ORD1226,150.0,Hyderabad,Electronics,Power Bank,2,125.77,0.0,Cash,2024-04-06,3.0

In [70]:
df = df.drop(124)

In [71]:
df[df['orderid'] == 'ORD1226']

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
21,ORD1226,150.0,Hyderabad,Electronics,Power Bank,2,6288.5,0.0,Cash,2024-04-06,3.0

In [72]:
df[df['orderid'] == 'ORD1001']

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
84,ORD1001,-5.0,DELHI,Sports,Dumbbell,5,450.71,5.0,Credit Card,2023-10-01,5.0
222,ORD1001,-5.0,Delhi,Clothing,Jeans,0,276.87,20.0,Credit Card,2024-08-25,2.0
284,ORD1001,41.0,Pokhara,Electronics,Power Bank,2,275.08,0.0,Net Banking,2023-01-03,NaN
308,ORD1001,-5.0,Hyderabad,Books,Textbook,1,347.01,0.0,Net Banking,2023-12-02,5.0
385,ORD1001,150.0,mumbai,Electronics,USB Cable,2,41.65,0.0,Credit Card,2023-11-28,NaN
551,ORD1001,150.0,Delhi,Beauty,Face Cream,1,190.40,0.0,Unknown,2023-10-09,NaN

In [74]:
df = df.drop([84,222,308,385,551])

In [75]:
df[df['orderid'] == 'ORD1001']

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
284,ORD1001,41.0,Pokhara,Electronics,Power Bank,2,275.08,0.0,Net Banking,2023-01-03,NaN

In [77]:
df.duplicated(subset=['orderid']).sum()

np.int64(0)

In [78]:
df.duplicated().sum()

np.int64(0)

## **Invalid values**

### Ages: check `.describe()` / sort values — anything negative or above ~100 is garbage

In [79]:
df['customer_age'].describe()

count    546.000000
mean      61.703297
std       58.761373
min       -5.000000
25%       19.250000
50%       46.000000
75%      150.000000
max      150.000000
Name: customer_age, dtype: float64

In [87]:
df['customer_age'].sort_values().head()

215   -5.0
530   -5.0
306   -5.0
120   -5.0
122   -5.0
Name: customer_age, dtype: float64

In [88]:
df['customer_age'].sort_values().tail()

328    150.0
331    150.0
332    150.0
439    150.0
564    150.0
Name: customer_age, dtype: float64

In [89]:
df[df['customer_age']< 0]

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
6,ORD1514,-5.0,Chennai,Beauty,Face Mask,0,433.70,0.0,UPI,2024-12-24,NaN
10,ORD1475,-5.0,DELHI,Electronics,Laptop Stand,3,266.21,0.0,Debit Card,2023-06-09,4.0
12,ORD1113,-5.0,Delhi,Clothing,Cap,5,465.20,0.0,Credit Card,10/03/2023,4.0
22,ORD1339,-5.0,Mumbai,Clothing,Hoodie,1,239.72,20.0,Debit Card,2024-11-28,3.0
30,ORD1486,-5.0,Hyderabad,Books,Comic,0,451.07,0.0,Net Banking,2023-05-25,NaN
...,...,...,...,...,...,...,...,...,...,...,...
541,ORD1031,-5.0,Mumbai,Home & Kitchen,Blender,1,305.73,0.0,UPI,2024-10-11,3.0
545,ORD1487,-5.0,Mumbai,Electronics,USB Cable,2,27.50,15.0,Credit Card,2024-12-14,4.0
548,ORD1150,-5.0,Pokhara,Home & Kitchen,Cutting Board,-1,142.93,0.0,Credit Card,2024-02-12,4.0
557,ORD1110,-5.0,Pokhara,Electronics,USB Cable,0,43.11,20.0,Net Banking,01/06/2023,NaN
560,ORD1457,-5.0,Hyderabad,Clothing,Jacket,1,10.62,0.0,UPI,2024-11-13,1.0

In [90]:
df[df['customer_age']> 100]

,orderid,customer_age,city,category,product_name,quantity,price,discount_pct,payment_method,order_date,rating
2,ORD1411,150.0,Bangalore,Toys,Doll,-1,163.06,20.0,Net Banking,01/05/2023,NaN
3,ORD1477,150.0,Mumbai,Electronics,Power Bank,0,41.53,0.0,UPI,26/01/2024,5.0
8,ORD1363,150.0,Unknown,Toys,Action Figure,5,231.84,0.0,Unknown,2023-12-06,5.0
9,ORD1313,150.0,Bangalore,Home & Kitchen,Lamp,0,17.55,0.0,Unknown,2024-05-06,5.0
21,ORD1226,150.0,Hyderabad,Electronics,Power Bank,2,6288.50,0.0,Cash,2024-04-06,3.0
...,...,...,...,...,...,...,...,...,...,...,...
553,ORD1127,150.0,Delhi,Home & Kitchen,Coffee Mug,1,409.92,15.0,Debit Card,2024-09-08,NaN
555,ORD1045,150.0,Delhi,Sports,Dumbbell,1,133.10,0.0,Cash,2024-11-02,4.0
556,ORD1314,150.0,mumbai,Home & Kitchen,Frying Pan,5,481.51,15.0,Cash,2024-05-15,3.0
558,ORD1059,150.0,mumbai,Home & Kitchen,Lamp,5,27.39,0.0,Unknown,2024-12-25,5.0
564,ORD1123,150.0,Delhi,Sports,Jump Rope,1,162.41,20.0,UPI,22/03/2024,4.0

In [93]:
df = df.drop(df[df['customer_age']< 0].index)

In [94]:
df = df.drop(df[df['customer_age']>100].index)

### Quantity: 0 or negative doesn't make sense for an order — decide drop vs investigate